#!/bin/bash

# Reset text to normal
reset=$(tput sgr0)

# Reset text, red background, red foreground
r=$(tput sgr0; tput setab 1; tput setaf 1)

# Reset text, white background, white foreground
w=$(tput sgr0; tput setab 7; tput setaf 7)

# Print. Just saving some line space
p() {
 echo -e "${@}"
}

# Could make lines functions, but this view is more readable
printf "\n"
p "${reset} ${r} █████████████████████${reset}"
p "${reset} ${r} ████████${w}█████${r}████████${reset}"
p "${reset} ${r} ████████${w}█████${r}████████${reset}"
p "${reset} ${r} ███${w}███████████████${r}███${reset}"
p "${reset} ${r} ███${w}███████████████${r}███${reset}"
p "${reset} ${r} ████████${w}█████${r}████████${reset}"
p "${reset} ${r} ████████${w}█████${r}████████${reset}"
p "${reset} ${r} █████████████████████${reset}"

# Reset again
p "${reset}"

