#!/bin/sh

(cd ~/.diary; find . -type f -name '*-*-*' | sort | xargs -n1 -I{} sh -c "printf '\n ------------------------------- {} ------------------------------- \n\n' | tr -d ./ ; cat {}" | nl | less)

