#!/bin/bash
# Add all iTunes music to cmus library

dir="$HOME/Music/iTunes/iTunes Media/Music"

{
	find "$dir" -type f -iname '*.mp3'
	find "$dir" -type f -iname '*.m4a'
	find "$dir" -type f -iname '*.wav'
} > ~/.config/cmus/lib.pl
