#!/usr/bin/env python

import sys
import numpy as np
import matplotlib.pyplot as pl

A = np.loadtxt('/dev/stdin', delimiter=',')

if len(sys.argv) >= 3:
	start = float(sys.argv[1])
	end = float(sys.argv[2])
else:
	start = A.min()
	end = A.max()
if len(sys.argv) >= 4:
	N = int(sys.argv[3])
else:
	# N = int(0.5 + end - start + 1)
	N = 50


pl.hist(A, bins=np.linspace(start, end, N))
pl.title('/dev/stdin')
pl.show()
