#!/bin/bash

# Finds the file name of the currently playing song and if it's named
# <name>-<soundcloud id>.mp3 (like youtube-dl does it) it gets that id
# and finds out more using the soundcloud api

client_id=$(cat ~/.soundcloud-api-key)

re='^[0-9]+$'

track_id=$(mpc -f '%file%' | head -1 | rev | cut -d- -f1 | rev | cut -d. -f1)
if ! [[ $track_id =~ $re ]] ; then
	echo Could not find soundcloud ID of current track > /dev/stderr
	exit 1
fi

url="http://api.soundcloud.com/tracks/$track_id.json?client_id=$client_id"

# Print API request url
if [ "$1" = -u ] || [ "$1" = -p ]; then
	echo "$url"
	exit
fi

# Print all info
if [ "$1" = -a ]; then
	curl -s "$url" | jq
	exit
fi

# Print the cover url
if [ "$1" = -c ]; then
	curl -s "$url" | jq -r .artwork_url | sed 's/large/t500x500/g'
	exit
fi

# Show cover with feh
if [ "$1" = -f ]; then
	feh $(curl -s "$url" | jq -r .artwork_url | sed 's/large/t500x500/g') &
	exit
fi

# Open soundcloud page
if [ "$1" = -o ]; then
	xdg-open $(curl -s "$url" | jq -r .permalink_url)
	exit
fi

# Default: Print soundcloud link
curl -s "$url" | jq -r .permalink_url
