#!/bin/bash

client_id=$(cat ~/.soundcloud-api-key)

re='^[0-9]+$'

track_id=$(mpc -f '%file%' | head -1 | rev | cut -d- -f1 | rev | cut -d. -f1)
if ! [[ $track_id =~ $re ]] ; then
	echo Could not find soundcloud ID of current track > /dev/stderr
	exit 1
fi

url="http://api.soundcloud.com/tracks/$track_id.json?client_id=$client_id"

# Print all info
if [ "$1" = -a ]; then
	curl -s "$url" | jq
	exit
fi

# Print the cover url
if [ "$1" = -c ]; then
	curl -s "$url" | jq -r .artwork_url | sed 's/large/t500x500/g'
	exit
fi

# Show cover with feh
if [ "$1" = -f ]; then
	feh $(curl -s "$url" | jq -r .artwork_url | sed 's/large/t500x500/g') &
	exit
fi

# Default: Print soundcloud link
curl -s "$url" | jq -r .permalink_url
