#!/bin/bash

#                       Remove leading ws    Prepend the length and a :              Sort      Remove length and :
env LC_ALL='C' cat $@ | sed 's/^[ \t]*//g' | awk '{printf("%d:%s\n", length, $0)}' | sort -n | cut -d':' -f2-

