#!/bin/sh
# Converts newline-separated numbers (or strings in general)
# to python and haskell compatible list literals
# Use -s to enclose each line in "double quotes" -> string
# Use -t to enclose each line in (parentheses) -> tuple

filter () {
	awk 'length {print}'
}

escape () {
	sed 's/"/\\"/g'
}

join_and_surround () {
	tr '\n' ',' | sed 's/\(.*\)/[\1]/g'
}

if test "$1" = '-s'; then
	shift
	cat $@ | filter | escape | sed 's/\(.*\)/"\1"/g' | join_and_surround
elif test "$1" = '-t'; then
	shift
	cat $@ | filter | escape | sed 's/\(.*\)/(\1)/g' | join_and_surround
else
	# Same as above except no quote escaping
	cat $@ | filter | join_and_surround
fi
