#!/bin/sh

# Signal to i3blocks so the song refreshes in the bar
pkill -RTMIN+11 i3blocks

# Put the album art in /tmp/albumart.jpg
/home/balduin/scripts/refresh-albumart.sh

logfile="/home/balduin/.mpdcron/logs/log-$(date +'%Y-%m-%d').csv"
outfile=~/testfifo
# echo $logfile > $outfile

# printenv | nl >> $outfile

if [ "$MPD_STATUS_STATE" != 'play' ]; then
	printf '%s,status:::%s\n' $(date +%s) "$MPD_STATUS_STATE" >> "$logfile"
else
	printf '%s,%s\n' $(date +%s) "$MPD_SONG_URI" >> "$logfile"
fi
