#!/usr/bin/env bash

percentage=$(cmus-percentage)

# Default length is 100, but overridden by $1
length=${1:-"100"}

past=$(printf "%d * (%d / 100)\n" $length $percentage | bc -l | cut -d'.' -f1)

# Set past to 0 if empty because bc writes '.25' instead of '0.25', so
# we end up with an empty string when applying the above 'floor function'
[[ -z "$past" ]] && past=0

progress $past $length
