#!/bin/bash
# Calculate the numerical derivative of a list of numbers,
# given via stdin or a file named by $1

while read line
do
	if [ "$oldline" ]; then
		# Subtract last two lines      Fix bc's output (.0 -> 0.0)
		echo "$line - $oldline" | bc | sed 's/^\./0\./g;s/^-\./-0\./g'
	fi
	oldline=$line
done < "${1:-/dev/stdin}"
