#!/bin/bash

#
# Print human-readable size of file or directory tree
#

# to pass -h option to ls and du
if [[ $1 == -* ]]; then
	options="$1"
	shift
fi

# If the file is a symlink, use the file it points to
if test -L "$1"; then
	file=$(readlink $(echo "$1" | tr -d '/'))
else
	file=$1
fi

# If it's a directory, print out the size of all its contents
if test -d "$file"; then
	gdu -sb $options "$file" | cut -f1
fi

# If it's a file, print its size
if test -f "$file"; then
	ls -la $options "$file" | awk -F " " '{print $5}' | sed 's/,/./g'
fi
