#!/bin/bash

#
# Print human-readable size of file or directory tree
#

# to pass -h option to ls and du
if [[ $1 == -* ]]; then
	options="$1"
	shift
fi

for i in "$@"; do
	# If the file is a symlink, use the file it points to
	if test -L "$i"; then
		file=$(readlink $(echo "$i" | tr -d '/'))
	else
		file=$i
	fi

	# If it's a directory, print out the size of all its contents
	if [ -d "$file" ] || [ -f "$file" ]; then
		gdu -sb $options "$file" | cut -f1
	else
		echo fsize: "$file" is not a file or directory 1>&2
	fi
done
