#!/bin/bash
# Calculate the running sum of a list of numbers,
# given via stdin or a file named by $1

# Set an initial value by using the -s option:
# $ seq 3 > numbers
# $ integ numbers
# 1
# 3
# 6
# $ integ -s 100 numbers
# 101
# 103
# 106

sum=0

if [ "$1" = -s ]; then
	sum="$2"
	shift 2
fi

while read line
do
	sum=$(echo "$sum + $line" | bc)
	echo $sum
done < "${1:-/dev/stdin}"
