#!/bin/bash
# Prints amount of free memory in bytes
#          get free 4096b-blocks remove non-digits        * 4096 to get bytes
echo $(( $(vm_stat | grep free | tr -C -d '[[:digit:]]' | sed 's/$/*4096/g') ))
