#!/bin/sh
# Converts newline-separated numbers (or strings in general)
# to python and haskell compatible list literals
# Use -s to enclose each line in "double quotes"

if test "$1" = '-s'; then
	# Escape double quotes, surround,     concatenate,  enclose in [...]
	cat $@ | sed 's/"/\\"/g' | sed 's/\(.*\)/"\1"/g' | tr '\n' ',' | sed 's/^/[/g;s/,$/]/g'
else
	cat $@ | tr '\n' ',' | sed 's/^/[/g;s/,$/]/g'
fi
