#!/bin/sh
# Converts newline-separated numbers (or strings in general)
# to python and haskell compatible list literals
# Use -s to enclose each line in "double quotes"

if test "$1" = '-s'; then
	shift
	#        Remove empty lines         Escape double quotes                      Newline to commas
	cat $@ | awk 'length > 0 {print}' | sed 's/"/\\"/g' | sed 's/\(.*\)/"\1"/g' | tr '\n' ',' | sed 's/^/[/g;s/,$/]/g'
	#                                                     Surround with double quotes           Surround with []
else
	# Same as above except no quote escaping
	cat $@ | awk 'length > 0 {print}' | tr '\n' ',' | sed 's/^/[/g;s/,$/]/g'
fi
