#!/bin/bash
# Wrapper for GNU units that accepts input like the google search box
# Converts '100 km to mil' to:
#	echo -e '100 km \n mil'
# which results in:
# You have: 100 km
# You want: mil
#     * 3.9370079e+09
#     / 2.54e-10
# The answer is then parsed and printed.

# If there are no arguments, read from stdin
if [ $# -eq 0 ]; then
	while read line; do
		$0 "$line"
	done;
fi

# Otherwise, concatenate the arguments and use them as input
# Convert 'to' to a newline
n='\
'
result=$(echo "$@" | sed "s/ to /$n/g" | gunits | grep -i '*' | cut -d'*' -f2 | tr -d ' ')
if [ $(echo $result | wc -c) -eq 1 ]; then
	echo 'Error'
else
	echo $result
fi
